apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops  
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
      - name: devsecops-container
        image:
        ports:
        - containerPort: 5000
